### ISSUE TITLE
Hex documentation is missing

### ISSUE THREAD

**Issue by tispratik** [mykewould/crutches#103]
http://hexdocs.pm/crutches/ does not open.

**Comment by duijf** [comment]
Hey @tispratik, thanks for the report! I'll see what I can do tomorrow, but I'm not sure I have the access to do so.

@mykewould think you might need to step in here.

**Comment by mykewould** [comment]
I'll take a look!

**Comment by mykewould** [comment]
Ok, they've been added, but I think it may take a moment for the hosting to be resolved. I'll check back in a few hours.

**Comment by tispratik** [comment]
Works! Thanks.
