### ISSUE TITLE
Number.as_rounded is broken on 1.4

### ISSUE THREAD

**Issue by duijf** [mykewould/crutches#112]
See https://travis-ci.org/mykewould/crutches/builds/191438234

On Elixir 1.4, the result of `Number.as_rounded` is different from the result that earlier Elixir versions gave. These should all be consistent and of the old behaviour

I don't have time to work on this, currently; so this is up for grabs!

**Comment by carlism** [comment]
I had a go at this:  https://github.com/mykewould/crutches/pull/115

**Comment by duijf** [comment]
Tests are passing again!
