### ISSUE TITLE
Decide on removal of underscore/1 and camelize/1

### ISSUE THREAD

**Issue by duijf** [mykewould/crutches#113]
`Crutches.String.underscore/1` and `Crutches.String.camelize/1` are currently just delgates to the same functions in the `Macro` module in the Elixir standard library.

Since the goal of Crutches is to be a supplement to functionality that is not in the standard library, we can probably remove these functions (they are also currently breaking the build on Elixir 1.1).

Thoughts?

**Comment by mykewould** [comment]
I agree with this.
