### ISSUE TITLE
Array#in_groups => List.in_groups

### ISSUE THREAD

**Issue by mykewould** [mykewould/crutches#12]
``` ruby
  # Splits or iterates over the array in +number+ of groups, padding any
  # remaining slots with +fill_with+ unless it is +false+.
  #
  #   %w(1 2 3 4 5 6 7 8 9 10).in_groups(3) {|group| p group}
  #   ["1", "2", "3", "4"]
  #   ["5", "6", "7", nil]
  #   ["8", "9", "10", nil]
  #
  #   %w(1 2 3 4 5 6 7 8 9 10).in_groups(3, '&nbsp;') {|group| p group}
  #   ["1", "2", "3", "4"]
  #   ["5", "6", "7", "&nbsp;"]
  #   ["8", "9", "10", "&nbsp;"]
  #
  #   %w(1 2 3 4 5 6 7).in_groups(3, false) {|group| p group}
  #   ["1", "2", "3"]
  #   ["4", "5"]
  #   ["6", "7"]
```

Convert [Array#in_groups](https://github.com/rails/rails/blob/master/activesupport/lib/active_support/core_ext/array/grouping.rb#L60) => List.in_groups

Hints to get started:
- in_groups should take 3 parameters, the last parameter is a function
- Convert Ruby comments into Elixir [doctests](http://elixir-lang.org/getting-started/mix-otp/docs-tests-and-pipelines.html)
- TDD to solve

Additional resources:
[List intro](http://elixir-lang.org/getting-started/basic-types.html)
[List documentation](http://elixir-lang.org/docs/v1.0/elixir/List.html)

**Comment by druzn3k** [comment]
I'm willing to close this issue. If anyone is already working on this or willing to, please tell me. Thanks!

**Comment by mykewould** [comment]
All yours @druzn3k!
