### ISSUE TITLE
Got an idea?

### ISSUE THREAD

**Issue by mykewould** [mykewould/crutches#20]
If you'd like to see something implemented into Crutches, please post it here. I'll do the leg work of writing up the documentation for the issue, I just need your ideas!

**Comment by druzn3k** [comment]
Yes! We should follow a style guide. I found https://github.com/niftyn8/elixir_style_guide that seems to have quite the following. I'm not quite sure if it's a good idea per se, but I found that if i follow a style guide, I’m more prone to focus on the quality of code, and it could be a good thing for new contributors. I'm not talking about a really strict application of the style guide, PRs should not be dropped if are not 100% compliant with the style guide or this would scare off contributions, but a more of a rule to "force" people to adapt the _elixir way_. What do you think @mykewould ?

**Comment by druzn3k** [comment]
Also, the `ActiveSupport::NumberHelper` module is quite interesting:
- number_to_currency
- number_to_delimited
- number_to_human 
- number_to_human_size
- number_to_percentage
- number_to_phone
- number_to_rounded

**Comment by mykewould** [comment]
+1 for a style guide and the numberHelper module. I'll work on creating issues to tackle both of those! Thanks @druzn3k

**Comment by jesuspc** [comment]
About NumberHelper, how to tackle the fact that ActiveSupport's NumberHelper relies on i18n to configure the format of most of the outputs?

**Comment by duijf** [comment]
@jesuspc, @mykewould; `en_US.UTF-8` first and then others when we figure out the `i18n` stuff?

Anyway, while I really like the fact that sharing ideas is encouraged, I think the best way to discuss them is to encourage people to open an issue for their specific idea. This would prevent these threads from getting out of hand by having different discussions taking place in the same thread.

Could be done by pointing it out in the `README` or contributing document.

**Comment by duijf** [comment]
The current `CONTRIBUTING.md` document encourages people to create a new issue when they have an idea or feature request. If everyone is okay with that workflow, then I guess this can be closed?

**Comment by druzn3k** [comment]
closing.
