### ISSUE TITLE
Array#to => List.to

### ISSUE THREAD

**Issue by mykewould** [mykewould/crutches#3]
Convert ActiveSupport Array#to to Crutches List.to

``` ruby
  # Returns the beginning of the array up to +position+.
  #
  #   %w( a b c d ).to(0)  # => ["a"]
  #   %w( a b c d ).to(2)  # => ["a", "b", "c"]
  #   %w( a b c d ).to(10) # => ["a", "b", "c", "d"]
  #   %w().to(0)           # => []
  #   %w( a b c d ).to(-2) # => ["a", "b", "c"]
  #   %w( a b c ).to(-10)  # => []
```

Hints to get started:
- Create a Crutches.List module
- Convert Ruby comments into Elixir [doctests](http://elixir-lang.org/getting-started/mix-otp/docs-tests-and-pipelines.html)
- TDD to solve

Additional resources:
[List intro](http://elixir-lang.org/getting-started/basic-types.html)
[List documentation](http://elixir-lang.org/docs/v1.0/elixir/List.html)

**Comment by druzn3k** [comment]
PR #14 should close this.
