### ISSUE TITLE
Crutches.Format.to_xml

### ISSUE THREAD

**Issue by mykewould** [mykewould/crutches#30]
More information to come. Generated from #7. 
- Copy/paste the provided ElixirDoc/DocTest
- Add xml_builder as a dependency (look into how to do that)
- Write the appropriate code to call the appropriate xml_builder functions.

**Comment by CyrusNuevoDia** [comment]
Formatting as JSON or XML is out of the scope of this project, at least for now.

**Comment by mykewould** [comment]
I'll put this in the .to_xml mega thread as well.
