### ISSUE TITLE
Continuous integration

### ISSUE THREAD

**Issue by duijf** [mykewould/crutches#34]
It could be worthwhile to adopt CI to get some feedback on tests in PRs. In addition, we get some awesome badges :)

There are a couple of services that I like and work with Elixir projects:
- [Travis CI](https://travis-ci.org/) continuous integration that checks the correctness of the code.
- [Inch CI](https://inch-ci.org/) feedback on documentation quality.

Curious to hear thoughts and opinions. If any help is needed to set it all up, I'll gladly help.

**Comment by jesuspc** [comment]
+1

**Comment by CyrusNuevoDia** [comment]
I'm down. I've added a `.travis.yml` config.

@duijf if you could confirm that it looks good (it's my first time using CI), let me know.
@mykewould login to [Travis CI](http://travis-ci.org) with your Github and enable it for this repo, if you could.

Edit: @mykewould dunno if it was you or me, but it's all working now.

**Comment by mykewould** [comment]
Travis and inch integrated! Thanks guys!

**Comment by mykewould** [comment]
@knrz I had enabled the account before I ran out the door, so adding the .travis.yml made it work :)

**Comment by duijf** [comment]
@knrz Yup, looks good :+1:. I've added the versions in the `.travis.yml` file to the README in #39 :)
