### ISSUE TITLE
Options.combine!

### ISSUE THREAD

**Issue by duijf** [mykewould/crutches#42]
Currently, I'm seeing something along these lines a lot:

``` elixir
@function_name [
  valid_options: [:some, :option],
  default_options: [
    some: "foo"
    option: "bar"
  ]
]
def function_name(args, opts \\ @function_name[:default_options])
def function_name(args, opts) do
  Crutches.Keyword.validate_keys!(opts, @function_name[:valid_options])
  options = Keyword.merge(@function_name[:default_options], opts)

  ...
end
```

I think it would be nice if we instead could write something like this:

``` elixir
@function_name [
  valid: [:some, :option],
  defaults: [
    some: "foo",
    option: "bar"
  ]
]
def function_name(args, opts \\ @function_name[:defaults])
def function_name(args, opts) do
  # This validates and merges the options, throwing on error.
  opts = Crutches.Options.combine!(opts, @function_name)

  ...
end
```

It is less code to keep track of, it makes the intent more clear and is a bit less to type. I also think it is a better API.

I'll work on this if we end up liking this. Going to be lots of work and be a little invasive to adopt this everywhere.

What kind of variants seem to be good? I have thought of:
- `Options.combine!(options, configuration)` &mdash; throwing
- `Options.combine(options, configuration)` &mdash; non-throwing
- `Options.combine!(options, configuration, combinator)` &mdash; throwing, with custom combinator.
- `Options.combine(options, configuration, combinator)` &mdash; non-throwing, with custom combinator.

Anything else? Feedback welcome :)

**Comment by jesuspc** [comment]
Great idea

**Comment by duijf** [comment]
@jesuspc Thanks!

I think it might be beneficial to put the functions in the `Crutches.Keyword` module in this one since they have more to do with option handling than with manipulating keyword lists.

**Comment by duijf** [comment]
PR is merged, closing.
