### ISSUE TITLE
Renaming Number.number_to_XYZ to Number.format_as_XYZ

### ISSUE THREAD

**Issue by druzn3k** [mykewould/crutches#44]
What do you think guys? Is this change in the naming scheme for better or worse?

**Comment by CyrusNuevoDia** [comment]
We could also rename the module to `NumberHelper`, and then go with `NumberHelper.to_delimited(n)`.

**Comment by duijf** [comment]
Did some thinking, and here are my two cents:
- We are eventually going to end up with more formatters for other types, Strings, Lists, etc.
- I really like the `as_xyz` naming (as opposed to `to_xyz`) for reasons I mentioned in #6, [here](https://github.com/mykewould/crutches/issues/6#issuecomment-124982392).

I suggest putting all functions having to do with formatting in a submodule of `Crutches.Format`. This would look like the following.
- `Crutches.Format.Number.as_delimited`
- `Crutches.Format.List.as_sentence`

I can see these benefits:
- Clear distinction between functions having to do with formatting and/or destructive operations and those with transformations.
- Code organisation.
- Short function name when wanted, long call form when wanted (we could provide a `__using__` macro to auto import/alias the functions).

**Comment by CyrusNuevoDia** [comment]
@duijf—you're spot-on! I agree completely. :+1: :shipit:

**Comment by druzn3k** [comment]
Ok, no problem, seems a good solution. This will be part of the 1.0.0 milestone. I will open the appropriate issues.

**Comment by druzn3k** [comment]
Started the conversion in PR #46
