### ISSUE TITLE
Array#to_xml => List.to_xml

### ISSUE THREAD

**Issue by mykewould** [mykewould/crutches#7]
``` ruby
  # Returns a string that represents the array in XML by invoking +to_xml+
  # on each element. Active Record collections delegate their representation
  # in XML to this method.
  #
  # All elements are expected to respond to +to_xml+, if any of them does
  # not then an exception is raised.
  #
  # The root node reflects the class name of the first element in plural
  # if all elements belong to the same type and that's not Hash:
  #
  #   customer.projects.to_xml
  #
  #   <?xml version="1.0" encoding="UTF-8"?>
  #   <projects type="array">
  #     <project>
  #       <amount type="decimal">20000.0</amount>
  #       <customer-id type="integer">1567</customer-id>
  #       <deal-date type="date">2008-04-09</deal-date>
  #       ...
  #     </project>
  #     <project>
  #       <amount type="decimal">57230.0</amount>
  #       <customer-id type="integer">1567</customer-id>
  #       <deal-date type="date">2008-04-15</deal-date>
  #       ...
  #     </project>
  #   </projects>
  #
  # Otherwise the root element is "objects":
  #
  #   [{ foo: 1, bar: 2}, { baz: 3}].to_xml
  #
  #   <?xml version="1.0" encoding="UTF-8"?>
  #   <objects type="array">
  #     <object>
  #       <bar type="integer">2</bar>
  #       <foo type="integer">1</foo>
  #     </object>
  #     <object>
  #       <baz type="integer">3</baz>
  #     </object>
  #   </objects>
  #
  # If the collection is empty the root element is "nil-classes" by default:
  #
  #   [].to_xml
  #
  #   <?xml version="1.0" encoding="UTF-8"?>
  #   <nil-classes type="array"/>
  #
  # To ensure a meaningful root element use the <tt>:root</tt> option:
  #
  #   customer_with_no_projects.projects.to_xml(root: 'projects')
  #
  #   <?xml version="1.0" encoding="UTF-8"?>
  #   <projects type="array"/>
  #
  # By default name of the node for the children of root is <tt>root.singularize</tt>.
  # You can change it with the <tt>:children</tt> option.
  #
  # The +options+ hash is passed downwards:
  #
  #   Message.all.to_xml(skip_types: true)
  #
  #   <?xml version="1.0" encoding="UTF-8"?>
  #   <messages>
  #     <message>
  #       <created-at>2008-03-07T09:58:18+01:00</created-at>
  #       <id>1</id>
  #       <name>1</name>
  #       <updated-at>2008-03-07T09:58:18+01:00</updated-at>
  #       <user-id>1</user-id>
  #     </message>
  #   </messages>
  #
```

Convert ActiveSupport [Array#to_xml](https://github.com/rails/rails/blob/master/activesupport/lib/active_support/core_ext/array/conversions.rb#L197) to Crutches List.to_xml

Hints to get started:
- Create a Crutches.List module (if it does not exist)
- Convert Ruby comments into Elixir [doctests](http://elixir-lang.org/getting-started/mix-otp/docs-tests-and-pipelines.html)
- TDD to solve
- Please incorporate additional tests into doctests. [Additional tests can be found here](https://github.com/rails/rails/blob/master/activesupport/test/core_ext/array/conversions_test.rb#L87)

Additional resources:
[List intro](http://elixir-lang.org/getting-started/basic-types.html)
[List documentation](http://elixir-lang.org/docs/v1.0/elixir/List.html)
[XML resources for Elixir](https://github.com/h4cc/awesome-elixir#xml)
[Parsing Elixir](http://elixirsips.com/episodes/028_parsing_xml.html)

**Comment by CyrusNuevoDia** [comment]
On one hand there's following ActiveSupport convention, on the other hand there's Elixir's module namespacing. I'm not sure a `Crutches.List.to_xml` function makes sense, particular because the current Elixir `List.to_x` functions are for converting primitives. 

Would a new module, say, `Crutches.Format` make sense as an umbrella? If we're thinking of making Crutches the swiss-army-knife of Elixir libraries, let's consider adding dependencies like [Poison](https://github.com/devinus/poison) to also have `to_json` in the `Crutches.Format` module if we choose to go down that path.

**Comment by druzn3k** [comment]
@knrz that's not a bad idea the `Crutches.Format` umbrella & the Poison dependency.

**Comment by mykewould** [comment]
I like that approach @knrz

As an aside, I was curious to see how this issue played out. Moving forward, I think I'll format these types of issues as "discussion". Then possibly a sort of "breakdown" party to move this into manageable chunks that people can tackle... I'm just brainstorming. I can also just leave "hard" and let the assumption be that additional discovery will need to take place.

**Comment by CyrusNuevoDia** [comment]
@mykewould I'm totally interested in fleshing it out as much as I can—I'm willing to tackle `to_xml` and `to_json` once we finalize on how we want to do them—but I'm afraid I won't be leaving enough for other members to contribute towards. What do you think?

**Comment by mykewould** [comment]
@knrz do you think we could break this into smaller chunks, allowing you to tackle/architect the bulk, while giving some to other members? I think that'd be ideal, but if it's too much, you can grab all of it.

EDIT: typo

**Comment by CyrusNuevoDia** [comment]
@mykewould 
Create two new issues, and let anyone handle them:
1. Crutches.Format.to_json
   1. Copy/paste the provided ElixirDoc/DocTest
   2. Add [poison](https://github.com/devinus/poison) as a dependency (look into how to do that) 
   3. Write the appropriate code to call the appropriate poison functions
2. Crutches.Format.to_xml
   1. Copy/paste the provided ElixirDoc/DocTest
   2. Add [xml_builder](https://github.com/joshnuss/xml_builder) as a dependency (look into how to do that)
   3. Write the appropriate code to call the appropriate xml_builder functions.

This'll provide an opportunity for beginners to add/manage dependencies.

edit: damn markdown formatting :stuck_out_tongue_closed_eyes:

**Comment by mykewould** [comment]
Formatting as JSON or XML is out of the scope of this project, at least for now.
