### ISSUE TITLE
Crutches.Range.overlaps?

### ISSUE THREAD

**Issue by jdl** [mykewould/crutches#73]
Compare two ranges and see if they overlap each other

```
## Examples

  iex> Range.overlaps?(1..5, 4..6)
  true 

  iex> Range.overlaps?(1..5, 7..9)
  false

```

**Comment by jdl** [comment]
I'll get something working and supply a pull request. Please let me know if _anything_ I'm doing is wrong or annoying.

**Comment by druzn3k** [comment]
:+1:

**Comment by druzn3k** [comment]
Just a few tips: 
- write a good documentation
- start building a _working_ prototype and then improve, don't try to optimize too early (if you are coming from a non-functional programming language it's difficult to adapt, more if you have years of experience with OOP for example)
- Ranges can be pattern-matched:

``` elixir
iex(1)> r = Range.new(1, 10)
1..10
iex(2)> %{first: fst, last: lst} = r
1..10
iex(3)> fst
1
iex(4)> lst
10
```

**Comment by jdl** [comment]
Cool. To show you where I was headed, this is what I have in my console so far.

```
iex(11)> a..b = 1..5
1..5
iex(12)> x..y = 4..6
4..6

iex(14)> a in x..y || b in x..y || x in a..b || y in a..b
true

iex(15)> x..y = 7..9
7..9
iex(16)> a in x..y || b in x..y || x in a..b || y in a..b
false
```

**Comment by druzn3k** [comment]
good :+1: you could also expand the issue (this is almost too simple) and build also a function that given two Range respond with a range that is the the overlap. I don't know if this is of any utility, but it's worth a try. In the worst case, we could remove it later.

 Example:

``` elixir
Crutches.Range.overlapping_range(1..5, 4..8) # => 4..5
Crutches.Range.overlapping_range(1..5, 5..8) # => 5
Crutches.Range.overlapping_range(1..5, 6..8) # => nil
```

**Comment by jdl** [comment]
People commonly want to find overlapping date ranges, so this might be the start of something useful. The opposite could be used for scheduling: Find a list of ranges within these two ranges that don't overlap. Probably too complicated to start with though.

**Comment by druzn3k** [comment]
Start with this, and if you are confident enough when you have finished you could step up your game and build the non-overlapping version! :)

**Comment by duijf** [comment]
@jdl Looks like a good start!

Some suggestions for names and another function that might be of use:
- `Range.intersection` for the overlap feature: `Range.intersection(1..5, 4..6) => 4..5`
- `Range.union` for combining two ranges (only when they have an intersection): `Range.union(1..5, 4..10) => 1..10`

Maybe there's more stuff from set theory that might be useful, but I have no idea. ([Here](https://s-media-cache-ak0.pinimg.com/736x/11/3d/46/113d4693d4edf453430927b4558f6640.jpg) is a cheatsheet of common operations, in case you are looking for more stuff to do :smile:)

**Comment by druzn3k** [comment]
For reference Aldo: [Set in the standard library of elixir](http://elixir-lang.org/docs/stable/elixir/Set.html)

**Comment by jdl** [comment]
This one: 

```
Crutches.Range.overlapping_range(1..5, 5..8) # => 5
```

Wouldn't that just be 5..5 ?

**Comment by jdl** [comment]
I have overlaps?, intersection, and union on a branch in my fork.

https://github.com/jdl/crutches/commit/bbe26dd509d242ab824c39ce37378b02cfe13a7f

**Comment by jdl** [comment]
It occurred to me tonight that Elixir might support ranges going backwards, and it does. So those methods don't work yet. 

```
Range.intersection(5..3, 2..4) === 2..3
```

would fail. I'll keep at it.

**Comment by jdl** [comment]
Fixed the bug. Now I have two commits on that branch, with two semi-explanatory commit messages. If I wanted to create a pull request, what's the best way to do that so that it's easy on the upstream side?

https://github.com/jdl/crutches/commit/e96259a0ecb0c2a20b8fe5576d0c146b13bbc78e

**Comment by druzn3k** [comment]
Rebase against master, squash everything in a single commit, write a proper commit message. :)

**Comment by jdl** [comment]
Squashed: https://github.com/jdl/crutches/commit/ddf5535d66601f9630bee1807ef38cb57f52b9b4

Pull request: https://github.com/mykewould/crutches/pull/74

Hopefully I didn't screw anything up.

**Comment by druzn3k** [comment]
On a first look seems good! When I'm at the PC a will take a better look and merge it.
