### ISSUE TITLE
Project status.

### ISSUE THREAD

**Issue by Axxiss** [mykewould/crutches#78]
As the idea of the project is to create kind of an Active Support migration. Would be nice to have a checklist of ActiveSupport features and what is already done. This will generate a better notion of the project status.

What do you think of this?

**Comment by druzn3k** [comment]
Some kind of comparison could be useful, but it shouldn't give misdirections on the path taken by the project: the goal is for this to take the role that ActiveSupport has for Rails, not to be a clone. Making a comparison could give the impression of being a clone (IMO). What do you think?

**Comment by Axxiss** [comment]
Agree that it could lead to some confusion.  To avoid this scenario I would
state loud and clear that is not intended to be a clone. Despite is not
intended to be one, at the beginning it probably will be kind of a clone,
but as time pass it will move in its own direction.

I think having this list can help people who's lurking around to have a
better idea of what can be done.

**Comment by druzn3k** [comment]
Do you want to write it @Axxiss? I could help you, if you need any help!  :+1:

**Comment by Axxiss** [comment]
Sure, no problem. Will ping you when I have something.

**Comment by druzn3k** [comment]
wonderful, thanks @Axxiss

**Comment by druzn3k** [comment]
closed with #80
