### ISSUE TITLE
"to" function name is misleading

### ISSUE THREAD

**Issue by eksperimental** [mykewould/crutches#86]
I was skimming through the docs, this one certainly called my attention.

to is generally used to convert data type from one type to another, such as in Enum.to_list/1, Float.to_string/1

I think Crutches.List.to/2 will make more sense to rename it Crutches.List.up_to/2
the thing is what are you gonna name "from".

personally I think having Enum.slice/3 there is not need to have such functions (and Enum will work with any enumerable, not just lists).

in a case you want to keep it , maybe Enum.slice_to Enum.slice_from would be more clear (but redundant IMO)

**Comment by eksperimental** [comment]
oops. i forgot to mention Crutches.String.to
but same, as with Enum.slice, but we can use String.slice/3

**Comment by CyrusNuevoDia** [comment]
:+1: Good point. I approve.

**Comment by duijf** [comment]
I agree that the naming is unclear and that they'd be better suited for the Enum module, although I'm not sure if I'd like to see them removed.

I like the way the following reads:

``` elixir
def foo(collection) do
  collection
  |> do_something
  |> and_another_thing
  |> Enum.up_to(9)
end
```

Better than:

``` elixir
def foo(collection) do
  collection
  |> do_something
  |> and_another_thing
  |> Enum.slice(0, 9)
  # Or
  # |> Enum.slice(0..9)
end
```

That is obviously just personal preference. I don't know if the readability weighs up to shipping another function that users need to find out about. (And lots of these "aliases" might not benefit the library)

Although I must admit I have no idea if and how much performance we're sacrificing with the extra function call. @eksperimental do you have an idea whether performance plays a role.

**Comment by eksperimental** [comment]
@duijf I wouldn't worry about the performance. you can use https://github.com/alco/benchfella to see if there is any performance penalty.
Since these are just wrappers, I think it would be better to write them as macros, where no penalty performace will happen.

personally I think that you are shooting yourself in the foot by adding functions that are already present in elixir with a different name. Surely it is more readable, but as you mentioned, you are running the risk of making your whole library unreadable by filling it up with functions that do not add anything new.

**Comment by eksperimental** [comment]
but it all depends on the aim of your library.

**Comment by CyrusNuevoDia** [comment]
@eksperimental we're running into the same choices Ruby devs needed to make. For example, what's the difference between `(1..9)` and `1.upto(9)`? There effectively isn't any.

Code is read more often than it is written, and it's a matter of communicating your intentions. Which of the following is better at stating intentions?

``` elixir
collection |> Enum.map(&function) |> Enum.select(&predicate) |> Enum.from(10)
# or
collection |> Enum.map(&function) |> Enum.select(&predicate) |> Enum.slice(10, -1)
```

As software developers we write tools to make our life easier. By your logic, we shouldn't have `if` and `else` constructs but rather `jump` statements. They do the same, no? 

At least re: naming, how about `slice_from` and `slice_to`?

**Comment by eksperimental** [comment]
@knrz `if` is a convenience macro, that translates to `case`, letting you write an `if`..`else` statement in one line instead of 4, https://github.com/elixir-lang/elixir/blob/40c70ffcfabfd9547b012bfceaeeac4d1c047e86/lib/elixir/lib/kernel.ex#L2319-L2322
the example with `to` and `from` are not doing that.

**Comment by duijf** [comment]
Alright, I'm going to summarise the discussion:
- `List.to`, `String.to` and `List.from` have unclear names because these words are also used in type conversions. I think everyone agrees here.
- `List.to` and `String.to` can be renamed to `Enum.up_to` and `String.up_to` (and I think `List.from` can be `Enum.starting_from`). I also assume everyone agrees this is more clear.
- There is disagreement and a separate discussion whether these functions are useful. This touches the greater point of, well ehrm, the point of aliases and whether they impose a burden on users of this library or whether they enhance the readability of their code. This is a finer point of discussion and is IMHO separate from confusing naming.

For now I propose the following:
1. Deprecate `List.to`, `String.to` and `List.from`.
2. Introduce new functions with the same functionality: `Enum.up_to`, `Enum.starting_from` and String variants.
3. Open a new issue discussing the point of aliases and criteria for including or removing them.

This fixes the concrete confusion ASAP, and allows us more time to discuss the more philosophical issue. We can always remove the newly introduced functions at a later time.

Does anyone have an issue with this approach?

**Comment by duijf** [comment]
By the way, I like `List.from` since it saves you from checking the size of the collection. You can only give `Enum.slice` a count and you can't tell it to just give you everything from some point to the end of the collection. (Would be a good PR to Elixir itself also).

**Comment by CyrusNuevoDia** [comment]
@duijf `List.from` is already in the standard library as `Enum.drop`.

**Comment by duijf** [comment]
@knrz Didn't know that. Good to know. What do you think about the approach I proposed?

**Comment by CyrusNuevoDia** [comment]
Agreed on the unclear names, but I'm thinking that maybe we should rename it like this:

``` elixir
String.take("The cat in the hat", 7) # instead of String.to
String.drop("Green eggs and ham", 6) # instead of String.from
```

We'd be analogous to the `Enum` protocol this way and the naming would suggest it works similarly to `Enum.drop` and `Enum.take`, which it does.

**Comment by knrz** [comment]
Here's the implementation, if anyone's interested:

```elixir
def drop(_, 0), do: ""
def drop(string, n) when is_binary(string) and is_integer(n) and n > 0 do
  String.slice(string, n..-1)
end

def take(_, 0), do: ""
def take(string, n) when is_binary(string) and is_integer(n) and n > 0 do
  String.slice(string, 0..(n - 1))
end
```

**Comment by eksperimental** [comment]
@duijf thanks for your write up.
But i would hold on deprecating anything until you make a decission on supporting alias or not, because it will be unnecessary, and if you decide to drop alias functions, then you will have two set of deprecated functions.

**Comment by eksperimental** [comment]
Just to add more fuel to the discussion, 
in adition to String.slice/3, we have String.binary_part/3 which seems to be the right way to do it.
read the section named "String and binary operations"
http://elixir-lang.org/docs/master/elixir/String.html
