### ISSUE TITLE
Add description to README and Crutches module

### ISSUE THREAD

**Issue by eksperimental** [mykewould/crutches#88]
Right now I am unable to know what the aim of the project is unless I know about what ActiveSupport is.
Also, a description in the module doc should be added so it will appear in the docs

**Comment by duijf** [comment]
Thank you for the feedback! I've pushed a new description in https://github.com/mykewould/crutches/commit/78f22688ccd69b51a85356c402ebee8f8244541d. Is it similar to what you had in mind?

**Comment by eksperimental** [comment]
Thats excellent. same could be added to module doc

**Comment by duijf** [comment]
Whoops, forgot about that. Changed what was there to the current description in https://github.com/mykewould/crutches/commit/4f6d49c38bc2472b640561b313ccb6e5b6d59c54. Thanks!
