### ISSUE TITLE
Remove Map's fetch_path/fetch_path!/get_path

### ISSUE THREAD

**Issue by mgwidmann** [mykewould/crutches#90]
Elixir provides this functionality in `get_in` and and update version with `put_in`:

http://elixir-lang.org/docs/stable/elixir/Kernel.html#get_in/2
http://elixir-lang.org/docs/stable/elixir/Kernel.html#put_in/3

**Comment by CyrusNuevoDia** [comment]
You're right — would you like to submit a PR or would you like me to handle it?

**Comment by mgwidmann** [comment]
I won't be able to do so until this weekend, so its up to you. Did you want to release a depreciation first?

**Comment by CyrusNuevoDia** [comment]
@duijf Deprecation?

**Comment by duijf** [comment]
Yeah probably good to do a soft deprecation first (print a warning, add notice to docs, add a TODO to remove the functions with 2.0).

**Comment by mgwidmann** [comment]
Submitted a PR #96 ... Wasn't sure where you wanted the TODO ...
