### ISSUE TITLE
Add Elixir copytight to NOTICE file

### ISSUE THREAD

**Issue by eksperimental** [mykewould/crutches#92]
Integer.digits/1 was taken from Elixir. It should be credited with the proper copyright notice.

I think we should also include the @doc in the function

**Comment by duijf** [comment]
Yup, this is needed. Thanks for catching this. Fixed in e777e5e1, docs added in 5b7809f.

By the way, as far as I know, merely including the function in an MIT is not a violation of the Apache license (as long as we don't make any changes to the code and provide attribution).

**Comment by eksperimental** [comment]
I think we should do it thinking about that in the future it will get modified for whatever reason.
also apache requires to include a copy of the license 
www.apache.org/licenses/LICENSE-2.0
Section 4, item 1
