### ISSUE TITLE
Should List.shorten/2 return nil or empty list when the enumerable is shorter than the amount to shorten by?

### ISSUE THREAD

**Issue by lpil** [mykewould/crutches#94]
Currently it return `nil`. I think empty list would be better, as then you can pipe this function into ones in the `Enum` module without having to pattern match on the return value to handle the possible fail case (`nil`).

**Comment by duijf** [comment]
First off, thanks for the suggestion and taking the initiative with the PR!

I have to say I disagree with the proposed change, though. IMO, functions should return errors when they encounter a fail case, not continue silently.

The problem you're encountering with pipelines is not a problem with the functions themselves, but with the fact that the `|>` operator from the standard library doesn't allow for composition of functions that have an error case (like monads in Haskell do).

Now, I would agree that the error reporting of `shorten/2` is not idiomatic, in that it doesn't return a tagged tuple (`{:ok, list}` on success or `{:error, reason}` on failure). If that were the case you could use a library like [elixir-pipes](https://github.com/batate/elixir-pipes) to handle the pipeline like so:

``` elixir
pipe_matching x, {:ok x},
  some_list
  |> Enum.filter(&some_condition/1)
  |> Crutches.List.shorten(4)
  |> some_other_transformation
```

If the filter operation would return an empty list, `List.shorten` would return `{:error, "Empty list"}` and the pipeline would stop. With `pipe_with/2` from the same library you could write the logic to tease `nil` values into empty lists.

Bottomline; I think functions should throw errors when they fail; the programmer should handle them. Therefore I'm closing this. The handling of `List.shorten/2` as we have it might not be idiomatic though. I'm opening another issue to discuss that.

If you don't agree with me or think I'm overlooking something, feel free to post so. I'll reopen the issue and your PR then.

**Comment by lpil** [comment]
> The problem you're encountering with pipelines is not a problem with the functions themselves, but with the fact that the |> operator from the standard library doesn't allow for composition of functions that have an error case (like monads in Haskell do).

Lists are effectively a monad. With the Enum module you take a function from `a -> b` and apply it to a wrapped value, the same way you do with Haskell's monads. In fact, there are prominent members of the Haskell community such as Erik Meijer that have said that you should always avoid the Maybe monad in favour of the list monad, where empty list is the fail case.

It would make the type signature nicer too.

``` elixir
@spec shorten([x], Integer) :: [x] | nil
# becomes
@spec shorten([x], Integer) :: [x]

```

But either way, I think that returning `nil` here is a bad idea, and a breaking change should be made to the API in order to make the users of this library more likely to handle the fail case cleanly.

**Comment by duijf** [comment]
> Lists are effectively a monad. With the Enum module you take a function from a -> b and apply it to a wrapped value, the same way you do with Haskell's monads.

Lists have a monad instance, but that is the definition of a Functor, not a monad. `bind` takes a function `a -> m b` and `m a` and returns `m b`: 

``` haskell
(>>=) :: m a -> (a -> m b) -> m b
```

(Btw, this does exist in Elixir in `Enum.flat_map` which takes would have the Haskell type signature of  `[a] -> (a -> [b]) -> [b]`&mdash; normal map would be more like `[a] -> (a -> [b]) -> [[b]]`)

> In fact, there are prominent members of the Haskell community such as Erik Meijer that have said that you should always avoid the Maybe monad in favour of the list monad, where empty list is the fail case.

I think failing silently is not a good idea and prefer the tagged tuple approach. The programmer is then free to write a transformation from `{:error, "empty list"}` to `[]` and using that in a pipeline when the situation calls for it or writing whatever logic needed in that situation to deal with that in a pipeline. See below.

``` elixir
# Name could be better
defp ok({:ok, list}), do: list
defp ok({:error, _reason}), do: []

# Usage
some_list
|> Enum.filter(&some_condition/1)
|> Crutches.List.shorten(1)
|> ok
|> other_transformation_possibly_on_empty_list
```

I'm in favour of doing the following:
1. Change `shorten/2` to return a tagged tuple to have more idiomatic error handling.
2. Maybe provide the `ok/1` function somewhere (might be a nice utility to have).

What do you think?

**Comment by CyrusNuevoDia** [comment]
@duijf Tooting my own horn, but [Towel](https://github.com/knrz/towel). Delegate the `Result.ok` and `Result.error`?
